apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openlab-scheduler
resources:
  - ../../base
commonLabels:
  environment: latest
commonAnnotations:
  version: 1.0.8-146af046--2023-06-23.1687481041 # {"$imagepolicy": "openlab-scheduler:scheduler-api-image-policy:tag"}
images:
  - name: "scheduler-api"
    newName: "registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-api"
    newTag: "1.0.8-146af046--2023-06-23.1687481041" # {"$imagepolicy": "openlab-scheduler:scheduler-api-image-policy:tag"}
# Adds elasticapm config to deployment
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  - target:
      kind: Deployment
    path: deployment-patch.yaml
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=scheduler-api-latest
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com
    behavior: merge
