apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  environment: latest
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: scheduler-api-
nameSuffix: -latest
# Facilitate kustomization name updating
#
configurations:
  - kustomizeconfig.yaml
commonAnnotations:
  version: 2.3.1-053877b9--2024-06-24.1719244495 # {"$imagepolicy": "openlab-scheduler:scheduler-api-image-policy-latest:tag"}
images:
  - name: "scheduler-api"
    newName: "registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-api"
    newTag: "2.3.1-053877b9--2024-06-24.1719244495" # {"$imagepolicy": "openlab-scheduler:scheduler-api-image-policy-latest:tag"}
patches:
  # Patches ingress with "latest--"
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  # Adds secrets to deployment
  - target:
      kind: Deployment
    path: deployment-patch.yaml
  # Adds secrets, root password to statefulset
  - target:
      kind: StatefulSet
    path: statefulset-patch.yaml
  # Incorporate vault-secrets
  #
  # adds `-latest` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-latest/vault-auth-patch.yaml
components:
  # Include environment-specific secrets
  - ./vault-secrets-latest
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
# Appends service name to base elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=scheduler-api-latest
    behavior: merge
