apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
  - ../../bases/nginx-unprivileged
  - ingress.yaml
  - Kptfile
  - resourcegroup.yaml # created by 'kpt live init'
  - serviceaccount.yaml
generatorOptions:
  annotations:
    kustomize.generated.resource: "true"
#
# # Package-specific configurations; update the values below to fit your app
#
# namePrefix: bsn-openlab-scheduler-
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=bsn-openlab-scheduler-latest
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com
# All SSL is terminated at ingresses
secretGenerator:
  - type: kubernetes.io/tls
    name: star-ltc-bcit-ca
    files:
      - secrets/tls.crt
      - secrets/tls.key
      # #
      # # # Enable this for local cluster development. See README.md
      # #
      # - name: gitlab-registry-credentials
      #   type: kubernetes.io/dockerconfigjson
      #   files:
      #     - .dockerconfigjson=secrets/.dockerconfigjson
patches:
  - target:
      kind: Deployment
    patch: |-
      # updates container name so that deployment-patch replaces, not adds to deployment
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: bsn-openlab-scheduler
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      # - target:
      #     kind: Deployment
      #   patch: |-
      #     - op: add
      #       path: /spec/template/spec/imagePullSecrets
      #       value: [name: gitlab-registry-credentials]
commonLabels:
  environment: latest
  app: bsn-openlab-scheduler
  app.kubernetes.io/name: bsn-openlab-scheduler
#
# Items below here are updated automatically by the pipeline
#
namespace: bsn-openlab-scheduler # kpt-set: ${DEPLOY_NAMESPACE}
commonAnnotations:
  version: v1.0.2-efc7ad30 # kpt-set: ${GIT_TAG}
images: # kpt-set: ${IMAGE_REF}
  - {name: "bsn-openlab-scheduler", newName: "registry.ltc.bcit.ca/web-apps/bsn-openlab-scheduler", newTag: "efc7ad30"}
