apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openlab-scheduler
resources:
  - ../../base
# Resource names in a shared namespace must be unique
#
namePrefix: scheduler-api-
commonLabels:
  environment: latest
commonAnnotations:
  version: 1.0.11-ec1a5a5c--2023-07-01.1688215371 # {"$imagepolicy": "openlab-scheduler:scheduler-api-image-policy:tag"}
images:
  - name: "scheduler-api"
    newName: "registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-api"
    newTag: "1.0.11-ec1a5a5c--2023-07-01.1688215371" # {"$imagepolicy": "openlab-scheduler:scheduler-api-image-policy:tag"}
# Patches ingress with "latest--" and deployment with annotations
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  - target:
      kind: Deployment
    path: deployment-patch.yaml
# Appends service name to base elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=scheduler-api-latest
    behavior: merge
components:
  - ./vault-secrets
