version: "3.9"

services:
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=isajrqwoihjwaor
      - MARIADB_DATABASE=openlab-scheduler
      - MARIADB_USER=bsnmysql
      - MARIADB_PASSWORD=bcitbsn491
    healthcheck:
      test: "mariadb $$MARIADB_DATABASE -u$$MARIADB_USER -p$$MARIADB_PASSWORD -e 'SELECT 1;'"
      timeout: 10s
      retries: 10
      interval: 5s
      start_period: 10s
    volumes:
      - api_db:/var/lib/mysql

  app:
    command:
      - /bin/sh
      - -c
      # - npm run test
      - npm start
    build: ./
    ports:
      - "8000:8000"
    environment:
      - MARIADB_ROOT_HOST=db
      - MARIADB_DATABASE=openlab-scheduler
      - MARIADB_USER=bsnmysql
      - MARIADB_PASSWORD=bcitbsn491
      - TZ=America/Vancouver
      - SECRET_KEY=ahuaejsdb
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  api_db: