version: "3.9"

services:


  app:
    command:
      - /bin/sh
      - -c
      # - npm run test
      - npm start
    build: ./
    ports:
      - 8000:8000
    environment:
      - MARIADB_ROOT_HOST=db
      - MARIADB_DATABASE=openlab-scheduler
      - MARIADB_USER=bsnmysql
      - MARIADB_PASSWORD=bcitbsn491
      - TZ=America/Vancouver
      - JWT_AUTH_SIGNING_KEY=insecureT0kenSigningKey
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app


  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=isajrqwoihjwaor
      - MARIADB_DATABASE=openlab-scheduler
      - MARIADB_USER=bsnmysql
      - MARIADB_PASSWORD=bcitbsn491
    healthcheck:
      test: "mariadb $$MARIADB_DATABASE -u$$MARIADB_USER -p$$MARIADB_PASSWORD -e 'SELECT 1;'"
      timeout: 10s
      retries: 10
      interval: 5s
      start_period: 10s
    volumes:
      - api_db:/var/lib/mysql


  jsdoc_builder:
    image: node:21-alpine
    command:
      - /bin/sh
      - -c
      - |
        ./node_modules/.bin/jsdoc -c ./jsdoc.conf.json -r
    working_dir: /build
    volumes:
      - .:/build
    depends_on:
      app:
        condition: service_started
      

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080

volumes:
  api_db: