services:
  app:
    command:
      - /bin/sh
      - -c
      # - npm run test
      - npm start
    build: ./
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=openlab-scheduler
      - POSTGRES_USER=bsnmysql
      - POSTGRES_PASSWORD=bcitbsn491
      - TZ=America/Vancouver
      - JWT_AUTH_SIGNING_KEY=insecureT0kenSigningKey
      - NODE_ENV=development
      # - NODE_ENV=test
      # - NODE_ENV=production
      - SUPERUSER=admin@bcit.ca
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: bsnmysql
      POSTGRES_PASSWORD: bcitbsn491
      POSTGRES_DB: openlab-scheduler
    healthcheck:
      test: "pg_isready -U bsnmysql -d openlab-scheduler"
      timeout: 10s
      retries: 10
      interval: 5s
      start_period: 10s
    volumes:  
      - api_db:/var/lib/postgresql/data 

  jsdocs:
    image: node:21-alpine
    command:
      - /bin/sh
      - -c
      - |
        ./node_modules/.bin/jsdoc -c ./jsdoc.conf.json -r
    working_dir: /build
    volumes:
      - .:/build
        
  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080

volumes:
  api_db:
