apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: scheduler-api
  template:
    spec:
      containers:
        - name: scheduler-api
          envFrom:
            - configMapRef:
                name: mariadb-config
            - secretRef:
                name: mariadb-credentials
