apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
  - ../../bases/bsn-openlab-scheduler
  - ingress.yaml
  - Kptfile
  - resourcegroup.yaml # created by 'kpt live init'
generatorOptions:
  annotations:
    kustomize.generated.resource: "true"
#
# # Package-specific configurations; update the values below to fit your app
#
# All SSL is terminated at ingresses
secretGenerator:
  - type: kubernetes.io/tls
    name: star-ltc-bcit-ca
    files:
      - secrets/tls.crt
      - secrets/tls.key
  - name: mariadb-credentials
    literals:
      - MARIADB_USER="review"
      - MARIADB_PASSWORD="example"
    behavior: merge
  - name: vault-secrets-override
    literals:
      - TZ="America/Vancouver"
      - MYSQL_DB="bsn-openlab-scheduler"
      - MYSQL_HOST="bsn-openlab-scheduler-mariadb-service"
      - MYSQL_USER="review"
      - MYSQL_PASSWORD="example"
      - SECRET_KEY="ahuaejsdb"
  #
  # # Enable this for local cluster development. See README.md
  #
  #- name: gitlab-registry-credentials
  #  type: kubernetes.io/dockerconfigjson
  #  files:
  #    - .dockerconfigjson=secrets/.dockerconfigjson
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
  # - target:
  #     kind: Deployment
  #   patch: |-
  #     - op: add
  #       path: /spec/template/spec/imagePullSecrets
  #       value: [name: gitlab-registry-credentials]
commonLabels:
  environment: review
#
# Items here are updated automatically by the pipeline
#
namespace: bsn-openlab-scheduler # kpt-set: ${DEPLOY_NAMESPACE}
commonAnnotations:
  version: latest # kpt-set: ${GIT_TAG}
images: # kpt-set: ${IMAGE_REF}
  - {
      name: bsn-openlab-scheduler,
      newName: registry.ltc.bcit.ca/web-apps/bsn-openlab-scheduler,
      newTag: latest,
    }

