# adds secrets to deployment
#
---
- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    secretRef:
      name: auth-signing-key

- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    secretRef:
      name: elastic-apm-token

- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    secretRef:
      name: postgres-credentials

- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    secretRef:
      name: saml-superuser