apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qcon
resources:
  - ../../base
commonLabels:
  environment: stable
commonAnnotations:
  version: stable # {"$imagepolicy": "openlab-scheduler:scheduler-api:tag"}
images:
  - name: "scheduler-api"
    newName: "registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-api"
    newTag: "stable" # {"$imagepolicy": "openlab-scheduler:scheduler-api:tag"}
# Adds elasticapm config and Vault agent annotations to deployment
#
patches:
- target:
    kind: Deployment
  path: deployment-patch.yaml
- target:
    kind: StatefulSet
  path: statefulset-patch.yaml
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=scheduler-api-stable
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com
