# adds secrets to deployment
#
---
- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    secretRef:
      name: mariadb-credentials

- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    secretRef:
      name: root-mariadb-password

