apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-api
  template:
    metadata:
      labels:
        app: scheduler-api
    spec:
      serviceAccountName: scheduler-api-serviceaccount
      containers:
        - name: scheduler-api
          image: scheduler-api
          env:
            - name: MARIADB_ROOT_HOST
              value: scheduler-api-mariadb-service
          envFrom:
            - configMapRef:
                name: mariadb-config
            - secretRef:
                name: mariadb-credentials
            - configMapRef:
                name: elasticapm-config
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: openlab-scheduler-data
              mountPath: /app/data
      volumes:
        - name: openlab-scheduler-data
          emptyDir: {}