apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# If workloads share a common namespace, set the `namePrefix` in the overlay
#   `kustomization.yaml` to avoid name collisions.
#
# namePrefix: scheduler-api-

resources:
  - ./mariadb
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml

commonLabels:
  app: scheduler-api
  app.kubernetes.io/name: scheduler-api

patches:

  # Remove kustomize-generated secret from base
  #
  - target:
      name: mariadb-credentials
      kind: Secret
    patch: |
      $patch: delete
      kind: Kustomization
      metadata:
        name: DOES NOT MATTER

  # Update statefulset to use secrets retrieved from Vault
  #
  - target:
      kind: StatefulSet
    path: statefulset-patch.yaml

configMapGenerator:

  # Generates elasticapm initial config
  #
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com

  # Sets mariadb db
  #
  - name: mariadb-config
    literals:
      - MARIADB_DATABASE=openlab-scheduler
    behavior: replace

