apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: scheduler-api-

resources:
  - mariadb
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml

commonLabels:
  app: scheduler-api
  app.kubernetes.io/name: scheduler-api


# Kustomize mariadb with app-specific settings
#
patches:
- path: statefulset-patch.yaml
  target:
    kind: StatefulSet
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: elasticapm-config
  target:
    kind: StatefulSet

configMapGenerator:
  - name: mariadb-config
    literals:
      - MARIADB_DATABASE=openlab-scheduler
    behavior: replace
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com

secretGenerator:
  - name: mariadb-credentials
    literals:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=Columbiabc1!
    behavior: merge

