apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: scheduler-api-

resources:
  - mariadb
  - deployment.yaml
  - ingress.yaml
  - serviceaccount.yaml

commonLabels:
  app: scheduler-api
  app.kubernetes.io/name: scheduler-api


# Kustomize mariadb with app-specific settings
#
patches:
  - path: statefulset-patch.yaml
    target:
      kind: StatefulSet

secretGenerator:
  - name: mariadb-credentials
    literals:
      - "MARIADB_USER=admin"
      - "MARIADB_PASSWORD=Columbiabc1!"
    behavior: merge

configMapGenerator:
  - name: mariadb-config
    literals:
      - MARIADB_DATABASE=openlab-scheduler
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=scheduler-api
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com

