apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
  labels:
    tier: postgres
spec:
  serviceName: postgres-service
  selector:
    matchLabels:
      tier: postgres
  template:
    metadata:
      labels:
        tier: postgres
    spec:
      serviceAccountName: scheduler-api-serviceaccount
      containers:
        - name: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
