apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
  labels:
    tier: mariadb
spec:
  serviceName: mariadb-service
  selector:
    matchLabels:
      tier: mariadb
  template:
    metadata:
      labels:
        tier: mariadb
    spec:
      serviceAccountName: scheduler-api-serviceaccount
      containers:
        - name: mariadb
          envFrom:
            - configMapRef:
                name: mariadb-config
