apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
  labels:
    tier: mariadb
spec:
  serviceName: "mariadb"
  selector:
    matchLabels:
      tier: mariadb
  template:
    metadata:
      labels:
        tier: mariadb
    spec:
      serviceAccountName: openlab-scheduler-serviceaccount
      containers:
        - name: mariadb
          image: mariadb
          env:
            - name: MARIADB_ROOT_HOST
              value: scheduler-api-mariadb-service
          envFrom:
            - configMapRef:
                name: mariadb-config
            - secretRef:
                name: mariadb-credentials