apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
  - mariadb
  - deployment.yaml
  - Kptfile
  - service.yaml
  - serviceaccount.yaml
generatorOptions:
  annotations:
    kustomize.generated.resource: "true"
#
# Package-specific configurations; update the values below to fit your app
#
namePrefix: bsn-openlab-scheduler-
configMapGenerator:
  - name: mariadb-config
    literals:
      - MARIADB_DATABASE=bsn-openlab-scheduler
secretGenerator:
  - name: mariadb-credentials
    literals:
      - "MARIADB_USER=admin"
      - "MARIADB_PASSWORD=Columbiabc1!"
    behavior: merge
patches:
  - path: statefulset-patch.yaml
    target:
      kind: StatefulSet
commonLabels:
  app: bsn-openlab-scheduler
  app.kubernetes.io/name: bsn-openlab-scheduler
