apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    tier: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    tier: frontend
  type: NodePort
