---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - auth-signing-key.yaml
  - elastic-apm-token.yaml
  - postgres-credentials.yaml
  - saml-superuser.yaml
  - star-ltc-bcit-ca.yaml
