---
# apiVersion: secrets.hashicorp.com/v1beta1
# kind: VaultDynamicSecret
# metadata:
#   name: mariadb-credentials
# spec:
#   vaultAuthRef: vault-auth
#   mount: database-mariadb
#   path: static-creds/mariadb-credentials
#   destination:
#     create: true
#     name: mariadb-credentials
#   # Restart these pods when secrets rotated
#   rolloutRestartTargets:
#   - kind: Deployment
#     name: deployment
#   - kind: StatefulSet
#     name: statefulset
# ---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mariadb-credentials
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  refreshAfter: 6h
  mount: apps
  path: scheduler-api/latest/mariadb-credentials
  destination:
    name: mariadb-credentials
    create: true


# # static-role with 24h password rotation - requires user "vault-mariadb-credentials" to be created at db init
# resource "vault_database_secret_backend_static_role" "scheduler-api-mariadb-credentials-latest" {
#   backend             = vault_mount.database-mariadb.path
#   rotation_period     = "86400"
#   rotation_statements = ["ALTER USER \"{{name}}\" WITH PASSWORD '{{password}}';"]

#   db_name             = vault_database_secret_backend_connection.scheduler-api-database-mariadb-latest.name
#   username            = "vault-mariadb"
#   name                = "scheduler-api-mariadb-credentials-latest"
# }

# vault write database-mariadb/static-roles/scheduler-api-mariadb-credentials-latest \
#     db_name=scheduler-api-mariadb-service \
#     rotation_statements=@rotation.sql \
#     username="vault-mariadb" \
#     rotation_period=86400