apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata: # kpt-merge: /kustomization
  name: kustomization
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'kustomize.config.k8s.io|Kustomization|default|kustomization'

resources:
  - statefulset.yaml
  - Kptfile
  - service.yaml

namePrefix: mariadb-

configMapGenerator:
  - name: config
    literals:
      - MARIADB_DATABASE=mariadb

secretGenerator:

  # root credentials rotated by Vault
  - name: credentials
    literals:
      - MARIADB_ROOT_PASSWORD=rootpassword

