apiVersion: apps/v1
kind: StatefulSet
metadata: # kpt-merge: /statefulset
  name: statefulset
  labels:
    tier: mariadb
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|StatefulSet|default|statefulset'
spec:
  serviceName: "mariadb"
  selector:
    matchLabels:
      tier: mariadb
  template:
    metadata:
      labels:
        tier: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
              name: mariadb
          envFrom:
            - secretRef:
                name: credentials
            - configMapRef:
                name: config
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - sh
                - -c
                - mariadb-admin -u$$MARIADB_USER -p$$MARIADB_PASSWORD ping
            periodSeconds: 5
          startupProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - sh
                - -c
                - mariadb $$MARIADB_DATABASE -u$$MARIADB_USER -p$$MARIADB_PASSWORD -e 'SELECT 1;'
            periodSeconds: 5
            failureThreshold: 12 # total 60s = 1min to startup and configure the database
