apiVersion: apps/v1
kind: StatefulSet
metadata: # kpt-merge: /statefulset
  name: statefulset
  labels:
    tier: mariadb
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|StatefulSet|default|statefulset'
spec:
  serviceName: "mariadb"
  selector:
    matchLabels:
      tier: mariadb
  template:
    metadata:
      labels:
        tier: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
              name: mariadb
          env:
            - name: MARIADB_ROOT_HOST
              value: service
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: MARIADB_ROOT_PASSWORD
