apiVersion: apps/v1
kind: StatefulSet
metadata: # kpt-merge: /statefulset
  name: statefulset
  labels:
    tier: mariadb
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|StatefulSet|default|statefulset'
spec:
  serviceName: "mariadb"
  selector:
    matchLabels:
      tier: mariadb
  template:
    metadata:
      labels:
        tier: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
              name: mariadb
          env:
            - name: MARIADB_ROOT_HOST
              value: mariadb-service
          envFrom:
            - configMapRef:
                name: mariadb-config
            - secretRef:
                name: mariadb-credentials
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - mysqladmin -u ${MARIADB_USER} -p${MARIADB_PASSWORD} ping
            periodSeconds: 10
          startupProbe:
            exec:
              command:
                - bash
                - -c
                - mysql -u ${MARIADB_USER} -p${MARIADB_PASSWORD} -e "SELECT 1"
            periodSeconds: 10
            failureThreshold: 12 # total 120s = 2min to startup and configure the database
