apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: root-mariadb-password
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  refreshAfter: 6h
  mount: apps
  path: scheduler-api/stable/root-mariadb-password
  destination:
    name: root-mariadb-password
    create: true