apiVersion: v1
kind: Service
metadata: # kpt-merge: /service
  name: service
  labels:
    tier: postgres
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|service'
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    tier: postgres
  clusterIP: None
