apiVersion: apps/v1
kind: StatefulSet
metadata: # kpt-merge: /statefulset
  name: statefulset
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|StatefulSet|default|statefulset'
spec:
  serviceName: postgres
  selector:
    matchLabels:
      tier: postgres
  template:
    metadata:
      labels:
        tier: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: credentials
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
            periodSeconds: 5
          startupProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
            periodSeconds: 5
            failureThreshold: 12 # total 60s = 1min to startup and configure the database
