name: Trigger auto deployment for scheduler-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/scheduler-api-AutoDeployTrigger-a56bd5ec-55d7-4607-ae8d-f82c0124f25d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCHEDULERAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCHEDULERAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCHEDULERAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: bcitltc.azurecr.io
          registryUsername: ${{ secrets.SCHEDULERAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCHEDULERAPI_REGISTRY_PASSWORD }}
          containerAppName: scheduler-api
          resourceGroup: LTC-ResourceGroup-CA
          imageToBuild: bcitltc.azurecr.io/scheduler-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


